[versions]
agp = "8.7.1"
androidxCoreKtx = "1.15.0"
androidxTestEspressoEspressoCore = "3.5."
autoimagesliderVersion = "1.3.9"
cardview = "1.0.0"
compiler = "4.12.0"
espressoCoreVersion = "3.5.1"
firebaseBom = "33.5.1"
gamesActivity = "3.0.5"
githubAutoimageslider = "1.4.0"
glide = "4.12.0"
junitVersion = "1.1.5"
kotlin = "1.9.24"
junit = "4.13.2"
espressoCore = "3.6.1"
appcompat = "1.7.0"
lottie = "6.5.2"
lottieVersion = "5.0.3"
material = "1.12.0"
activity = "1.9.3"
constraintlayout = "2.1.4"
googleGmsGoogleServices = "4.4.2"
picasso = "2.71828"

[libraries]
androidx-cardview = { module = "androidx.cardview:cardview", version.ref = "cardview" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "androidxCoreKtx" }
androidx-espresso-core-v35 = { module = "androidx.test.espresso:espresso-core", version.ref = "androidxTestEspressoEspressoCore" }
androidx-espresso-core-v351 = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
androidx-games-activity = { module = "androidx.games:games-activity", version.ref = "gamesActivity" }
androidx-junit-v115 = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
autoimageslider-v140 = { module = "com.github.smarteist:autoimageslider", version.ref = "githubAutoimageslider" }
compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "compiler" }
firebase-database = { module = "com.google.firebase:firebase-database" }
firebase-storage = { module = "com.google.firebase:firebase-storage" }
firebase-auth = { module = "com.google.firebase:firebase-auth" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
lottie = { module = "com.airbnb.android:lottie", version.ref = "lottie" }
lottie-v503 = { module = "com.airbnb.android:lottie", version.ref = "lottieVersion" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }
smarteist-autoimageslider = { module = "com.github.smarteist:autoimageslider", version.ref = "autoimagesliderVersion" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }
